=== co360/mooc/pluralsight/ws/xml-fundamentals/7/Chapter.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT chapter (title, summary, body)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT summary (para+)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT body (para+)>

=== co360/mooc/pluralsight/ws/xml-fundamentals/7/TwiceRememberedChapter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE chapter SYSTEM "Chapter.dtd">
<chapter>
	<title>The Land of the Twice Remembered</title>
	<summary>
		<para>Joe and the dinosaur find the omicra plant.</para>
		<para>The Omicra plants blossom. </para>
	</summary>
	<body>
		<para>Joe and the dinosaur find the omicra plant.</para>
		<para>The oil leaves reminded Joe his slider bike needed maintenace.</para>
	</body>
</chapter>
